# https://github.com/ollama/ollama/blob/main/docs/api.md

@host = http://localhost:11434
#@model = codellama
@model = llama3.2:1B
#@model = starcoder2
@embedding-model = nomic-embed-text:latest

### Generate a completion
POST {{host}}/api/generate
Content-Type: application/json

{
  "model": "{{model}}",
  "prompt": "Please introduce yourself",
  "stream": false,
  "options": {
    "temperature": 0.0
  },
  "keep_alive": 0
}

### Generate a chat completion
POST {{host}}/api/chat
Content-Type: application/json

{
  "model": "{{model}}",
  "messages": [
    {
      "role": "user",
      "content": "Please introduce yourself"
    }
  ]
}

### Unload model
POST {{host}}/api/generate
Content-Type: application/json

{
  "model": "{{model}}",
  "keep_alive": 0
}

### List Local Models
GET {{host}}/api/tags

### Show Model Information
POST {{host}}/api/show
Content-Type: application/json

{
  "name": "{{model}}",
  "verbose": false
}

### List Running Models
GET {{host}}/api/ps

### Generate Embeddings
POST {{host}}/api/embed
Content-Type: application/json

{
  "model": "{{embedding-model}}",
  "input": "Hi!",
  "keep_alive": 0
}
