services:

  chat:
    build:
      context: .
    image: ddl0x0d/genai/chat:latest
    depends_on:
#      - chroma
      - ollama
#      - pgvector
#      - qdrant
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command:
      - -c
      - /app/config.yaml
    ports:
      - "5005:5005"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./README.md:/app/README.md

  chroma:
    image: chromadb/chroma:0.6.3 # Jan 15, 2025 https://hub.docker.com/r/chromadb/chroma/tags
    # image: chromadb/chroma:1.0.13 # Jun 18, 2025 https://hub.docker.com/r/chromadb/chroma/tags
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/data

  ollama:
    image: ollama/ollama:0.9.2 # Jun 18, 2025 https://hub.docker.com/r/ollama/ollama/tags
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama

  pgvector:
    image: pgvector/pgvector:pg17 # Mar 6, 2025 https://hub.docker.com/r/pgvector/pgvector/tags
    environment:
      POSTGRES_USER: pgvector
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data

  # http://localhost:6333/dashboard
  qdrant:
    image: qdrant/qdrant:v1.14.1 # May 23, 2025 https://hub.docker.com/r/qdrant/qdrant/tags
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  chroma-data:
  pgvector-data:
  qdrant-data:
